# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'database' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for database

  pod 'RealmSwift'

  target 'databaseTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'databaseUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
